### ISSUE TITLE
Text manipulation gestures (e.g. double tap, tap & hold) do not seem to work on Android.

### ISSUE THREAD

**Issue by fadulalla** [psovit/rich_code_editor#15]
Hello

I have noticed that text manipulation gestures do not seem to work on Android.
For example, double tapping a word on the default material `TextField` highlights that word.
On a `CodeTextField`, the cursor just moves to the beginning of the word without highlighting it.
Similarly, tapping and holding a word does nothing but move the cursor to the beginning.

Also, this may be Android related only, but on some keyboards there are text gestures such as:
Sliding across the spacebar to move the cursor and dragging the backspace to the left to delete multiple words. 
The functionality works (sliding the the spacebar does move the cursor's underlying position, and sliding the backspace does delete multiple words) however there's no visual feedback.

Sliding backspace should highlight words-to-be-deleted before it deletes them, and sliding across the spacebar should move the blinking cursor as its position is being changed.

I was using my own Highlighter, but tested with the provided `DummyHighlighter` and the behaviour is still missing. Any thoughts?

Thanks for the great work by the way!

**rich_code_editor version**: 0.2.9
**flutter version**: 1.7.8+hotfix 3
**device:** Pixel 2XL running Android 10 (QP1A. 191105)

`flutter doctor -v`:
```
PS C:\Development\Flutter\project> flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.18362.476], locale en-GB)
    • Flutter version 1.7.8+hotfix.3 at C:\sdk\flutter
    • Framework revision b712a172f9 (5 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: c:\programdata\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\Faris\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Pixel 2 XL • 711KPPB0677296 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

### Edit
So I dug a bit into the code and found that the library has its own implementation of `TextSelectionControls`, and nothing but `Paste` is supported, how come? What's the reason behind this?

**Comment by psovit** [comment]
hi @fadulalla, you are correct that the library only has support for `Paste` function right now. When I initially started out this project, I wanted to reduce the complexity and thus only allowed paste option.
If this feature gets added in the later version, I will update in this issue here.

Thanks for trying out the project.

**Comment by psovit** [comment]
All the default text manipulation methods have now been implemented in v1.0.0.

**Comment by fadulalla** [comment]
Thank you!
I was going to take it for a spin but it seems like flutter 1.18 isn't supported (complains about missing implementations & non-existing getters).
I'll see if I can find time to fork and update, will open separate issue if I get somewhere!

**Comment by psovit** [comment]
Thanks @fadulalla .
I haven't tested it out with 1.18 yet. I will definitely update the plugin here when I upgrade my Flutter version.
