### ISSUE TITLE
RenderEditable.obscuringCharacter

### ISSUE THREAD

**Issue by Akashkumar201** [psovit/rich_code_editor#22]
/C:/package/flutter/.pub-cache/hosted/pub.dartlang.org/rich_code_editor-1.0.0/lib/rich_code_controller.dart:6:7: Error: The non-abstract class 'RichCodeEditingController' is missing implementations for these members:
 - TextEditingController.isSelectionWithinTextBounds
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RichCodeEditingController extends ValueNotifier<TextEditingValue> implements TextEditingController {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/package/flutter/packages/flutter/lib/src/widgets/editable_text.dart:229:8: Context: 'TextEditingController.isSelectionWithinTextBounds' is defined here.

  bool isSelectionWithinTextBounds(TextSelection selection) {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/package/flutter/.pub-cache/hosted/pub.dartlang.org/rich_code_editor-1.0.0/lib/rich_editable_code.dart:1617:34: Error: Too few positional arguments: 2 required, 1 given.
      ? () => controls.handleCopy(this)
                                 ^
/C:/package/flutter/.pub-cache/hosted/pub.dartlang.org/rich_code_editor-1.0.0/lib/rich_editable_code.dart:1705:29: Error: Getter not found: 'obscuringCharacter'.
      text = RenderEditable.obscuringCharacter * text.length;
                            ^^^^^^^^^^^^^^^^^^
2

FAILURE: Build failed with an exception.

**Comment by Akashkumar201** [comment]
**I am facing this issue again and again while running example **

**Comment by psovit** [comment]
This issue is now resolved with the latest upgrade to Flutter 1.22.5. Please use `rich_code_editor 1.0.5`. Thanks.

**Comment by Akashkumar06** [comment]
### **Thanks**
